[package]
name = "jsonui-lsp"
version = "0.0.1"
edition = "2021"
authors = ["CoolLoong"]
description = "A jsonui language server for vscode."
keywords = ["minecraft", "jsonui", "lsp", "vscode", "extension"]
categories = ["development-tools"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
jsonc-parser = { version = "0.23.0", features = ["serde"] }
tokio = { version = "1.39.3", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
log = "0.4.14"
flexi_logger = "0.28.5"
walkdir = "2.3"
museair = "0.2.0"
unicode-segmentation = "1.11.0"

[workspace]
members = ["vanillapack_define_gen"]

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "unpacked"
lto = true