[package]
name = "jsonui-lsp"
version = "0.0.1"
edition = "2021"
authors = ["CoolLoong"]
description = "A jsonui language server for vscode."
keywords = ["minecraft", "jsonui", "lsp", "vscode", "extension"]
categories = ["development-tools"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
ropey = "1.6.1"
tokio = { version = "1.39.3", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
log = "0.4.14"
env_logger = "0.11"
tree-ds = { version = "0.1.2", features = ["auto_id"] }

[workspace]
members = ["vanillapack_define_gen"]