resolver = "2"

[workspace]
members = ["crates/vanillapack_define_gen", "crates/jsonui_lsp"]

[profile.dev]
debug = true

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "unpacked"
lto = true