max_width = 105
fn_call_width = 105

comment_width = 150
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_imports = true
tab_spaces = 4
wrap_comments = true

struct_field_align_threshold = 50
enum_discrim_align_threshold = 50