[package]
name = "vanillapack_define_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.125"
jsonc-parser = { version = "0.26.2", features = ["serde"] }
