[package]
name = "vanillapack_define_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonc-parser = { version = "0.23", features = ["serde"] }
walkdir = "2.3"